# Generated by Django 5.0.6 on 2024-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=250)),
                ('descripcionProducto', models.CharField(max_length=250)),
                ('precioProducto', models.CharField(max_length=250)),
                ('imagenProducto', models.ImageField(upload_to='servicios')),
            ],
        ),
    ]
